#nginx-emptydir.yaml
apiVersion: v1
kind: Pod
metadata:
   name: emptyDir
   labels:
           app: nginx-app
spec:
   containers:
   - image: k8s.gcr.io/test-webserver
     mane: test-container
     volumeMounts:
     - name: cache-volume
       mountPath: /cache
   volumes:
   - name: cache-volume
     emptyDir: {}