apiVersion: v1
kind: PersistentVolume
metadata:

   name: data-pv

D
namespace: web
spec:
storageClassName: local-storage
capacity:
storage: 1Gi
accessModes:
- ReadWriteOnce
hostPath:
path: /mnt/data
